import { createBrowserRouter } from 'react-router-dom';
import { ProtectedRoute } from './ProtectedRoute';
import {
  S,
  LandingPage,
  LoginPage,
  SignupPage,
  ForgotPasswordPage,
  ResetPasswordPage,
  GroupsPage,
  GroupDetailPage,
  CreateGroupPage,
  ProfilePage,
  NotificationsPage,
  FaceAnchorSetupPage,
  PersonalBooksPage,
  PersonalBookReviewPage,
  BookTemplatesPage,
  BookCreatePage,
  BookEditorPage,
  BookPreviewPage,
  OrderPage,
  OrdersPage,
  OrderCompletePage,
  JoinPage,
  SharedViewerPage,
  NotFoundPage,
  ActivityFeedPage,
  BookListPage,
} from './RouteSuspense';

export const router = createBrowserRouter([
  { path: '/', element: <S><LandingPage /></S> },
  { path: '/login', element: <S><LoginPage /></S> },
  { path: '/signup', element: <S><SignupPage /></S> },
  { path: '/forgot-password', element: <S><ForgotPasswordPage /></S> },
  { path: '/reset-password/:token', element: <S><ResetPasswordPage /></S> },
  { path: '/join/:code', element: <S><JoinPage /></S> },
  { path: '/shared/:shareCode', element: <S><SharedViewerPage /></S> },
  {
    element: <ProtectedRoute />,
    children: [
      { path: '/groups', element: <S><GroupsPage /></S> },
      { path: '/groups/new', element: <S><CreateGroupPage /></S> },
      { path: '/groups/:groupId', element: <S><GroupDetailPage /></S> },
      { path: '/groups/:groupId/activity', element: <S><ActivityFeedPage /></S> },
      { path: '/groups/:groupId/books', element: <S><BookListPage /></S> },
      { path: '/profile', element: <S><ProfilePage /></S> },
      { path: '/notifications', element: <S><NotificationsPage /></S> },
      { path: '/groups/:groupId/face-anchor', element: <S><FaceAnchorSetupPage /></S> },
      { path: '/groups/:groupId/books/personal', element: <S><PersonalBooksPage /></S> },
      { path: '/groups/:groupId/books/personal/:bookId/review', element: <S><PersonalBookReviewPage /></S> },
      { path: '/groups/:groupId/books/templates', element: <S><BookTemplatesPage /></S> },
      { path: '/groups/:groupId/books/new', element: <S><BookCreatePage /></S> },
      { path: '/books/:bookId/editor', element: <S><BookEditorPage /></S> },
      { path: '/books/:bookId/preview', element: <S><BookPreviewPage /></S> },
      { path: '/books/:bookId/order', element: <S><OrderPage /></S> },
      { path: '/orders', element: <S><OrdersPage /></S> },
      { path: '/orders/:orderId/complete', element: <S><OrderCompletePage /></S> },
    ],
  },
  { path: '*', element: <S><NotFoundPage /></S> },
]);
