import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1776081849788 implements MigrationInterface {
    name = 'InitialSchema1776081849788'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying, "name" character varying(100) NOT NULL, "avatarUrl" character varying, "provider" character varying(20) NOT NULL DEFAULT 'local', "providerUserId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_provider_lookup" ON "users" ("provider", "providerUserId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."group_members_role_enum" AS ENUM('OWNER', 'MEMBER')`);
        await queryRunner.query(`CREATE TABLE "group_members" ("id" SERIAL NOT NULL, "groupId" integer NOT NULL, "userId" integer NOT NULL, "role" "public"."group_members_role_enum" NOT NULL DEFAULT 'MEMBER', "uploadCount" integer NOT NULL DEFAULT '0', "lastNotifiedAt" TIMESTAMP, "joinedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_86446139b2c96bfd0f3b8638852" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_group_members_group_user" ON "group_members" ("groupId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."groups_status_enum" AS ENUM('COLLECTING', 'EDITING', 'VOTING', 'ORDERED', 'COMPLETED', 'DELETED')`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "description" text, "coverImage" character varying(500), "inviteCode" character varying(20) NOT NULL, "status" "public"."groups_status_enum" NOT NULL DEFAULT 'COLLECTING', "ownerId" integer NOT NULL, "eventDate" date, "uploadDeadline" TIMESTAMP, "year" integer, "parentGroupId" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fbd67f706b662e3156ee502116b" UNIQUE ("inviteCode"), CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_groups_parent_group_id" ON "groups" ("parentGroupId") `);
        await queryRunner.query(`CREATE INDEX "idx_groups_owner_id" ON "groups" ("ownerId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_groups_invite_code" ON "groups" ("inviteCode") `);
        await queryRunner.query(`CREATE TABLE "user_face_anchor_samples" ("id" SERIAL NOT NULL, "anchorId" integer NOT NULL, "embedding" double precision array NOT NULL, "sourcePath" character varying(500), "confidence" double precision, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f1b1c7eee25c051fa9d5e1d8267" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_face_anchor_samples_anchor" ON "user_face_anchor_samples" ("anchorId") `);
        await queryRunner.query(`CREATE TABLE "user_face_anchors" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "groupId" integer NOT NULL, "embedding" double precision array NOT NULL, "sampleCount" integer NOT NULL DEFAULT '1', "threshold" double precision NOT NULL DEFAULT '0.6', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_598e34fae6ff11694bcf2b88f87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_user_face_anchors_group" ON "user_face_anchors" ("groupId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_user_face_anchors_user_group" ON "user_face_anchors" ("userId", "groupId") `);
        await queryRunner.query(`CREATE TABLE "photos" ("id" SERIAL NOT NULL, "groupId" integer NOT NULL, "uploaderId" integer, "kakaoName" character varying(100), "filename" character varying(255) NOT NULL, "originalFilename" character varying(255) NOT NULL, "mimetype" character varying(50) NOT NULL, "size" integer NOT NULL, "chapter" character varying(100), "width" integer, "height" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5220c45b8e32d49d767b9b3d725" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_photos_kakao_name" ON "photos" ("groupId", "kakaoName") `);
        await queryRunner.query(`CREATE INDEX "idx_photos_group_chapter" ON "photos" ("groupId", "chapter") `);
        await queryRunner.query(`CREATE INDEX "idx_photos_uploader_id" ON "photos" ("uploaderId") `);
        await queryRunner.query(`CREATE INDEX "idx_photos_group_id" ON "photos" ("groupId") `);
        await queryRunner.query(`CREATE TABLE "photo_faces" ("id" SERIAL NOT NULL, "photoId" integer NOT NULL, "groupId" integer NOT NULL, "embedding" double precision array NOT NULL, "bboxX" integer NOT NULL, "bboxY" integer NOT NULL, "bboxWidth" integer NOT NULL, "bboxHeight" integer NOT NULL, "confidence" double precision NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3113b2dcbbd3fd2a30927aa2b36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_photo_faces_group" ON "photo_faces" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "idx_photo_faces_photo" ON "photo_faces" ("photoId") `);
        await queryRunner.query(`CREATE TABLE "book_pages" ("id" SERIAL NOT NULL, "bookId" integer NOT NULL, "pageNumber" integer NOT NULL, "photoId" integer, "chapterTitle" character varying(100), "caption" character varying(500), "contentTemplateUid" character varying, "templateParams" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1d86ec4b294faa5fa041bd6a54e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_book_pages_book_id" ON "book_pages" ("bookId") `);
        await queryRunner.query(`CREATE TYPE "public"."books_booktype_enum" AS ENUM('SHARED', 'PERSONAL')`);
        await queryRunner.query(`CREATE TYPE "public"."books_status_enum" AS ENUM('DRAFT', 'UPLOADING', 'PROCESSING', 'READY', 'ORDERED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "books" ("id" SERIAL NOT NULL, "groupId" integer NOT NULL, "title" character varying(100) NOT NULL, "subtitle" character varying(200), "bookType" "public"."books_booktype_enum" NOT NULL DEFAULT 'SHARED', "ownerUserId" integer, "templateUid" character varying, "bookSpecUid" character varying NOT NULL, "theme" character varying, "status" "public"."books_status_enum" NOT NULL DEFAULT 'DRAFT', "sweetbookBookUid" character varying, "externalRef" character varying, "coverPhotoId" integer, "pageCount" integer NOT NULL DEFAULT '0', "shareCode" character varying(8), "isShared" boolean NOT NULL DEFAULT false, "coverTemplateUid" character varying, "coverParams" json, "createdById" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f3f2f25a099d24e12545b70b022" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_books_share_code" ON "books" ("shareCode") WHERE "shareCode" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_books_sweetbook_uid" ON "books" ("sweetbookBookUid") WHERE "sweetbookBookUid" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_books_group_id" ON "books" ("groupId") `);
        await queryRunner.query(`CREATE TYPE "public"."order_groups_status_enum" AS ENUM('COLLECTING', 'CONFIRMED', 'ORDERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "order_groups" ("id" SERIAL NOT NULL, "bookId" integer NOT NULL, "groupId" integer NOT NULL, "initiatedBy" integer NOT NULL, "estimatedPrice" numeric(10,2), "status" "public"."order_groups_status_enum" NOT NULL DEFAULT 'COLLECTING', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3343f5e3104fdccbe45376f7112" UNIQUE ("bookId"), CONSTRAINT "REL_3343f5e3104fdccbe45376f711" UNIQUE ("bookId"), CONSTRAINT "PK_6ea7fe44386fee9a655142632a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_order_groups_group_id" ON "order_groups" ("groupId") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('PENDING', 'REJECTED', 'SUBMITTING', 'PAID', 'PDF_READY', 'CONFIRMED', 'IN_PRODUCTION', 'ITEM_COMPLETED', 'PRODUCTION_COMPLETE', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'CANCELLED_REFUND', 'ERROR')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "orderGroupId" integer NOT NULL, "ordererId" integer NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'PENDING', "sweetbookOrderUid" character varying, "idempotencyKey" character varying NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "recipientName" character varying(50), "recipientPhone" character varying(20), "recipientAddress" character varying(500), "recipientZipCode" character varying(10), "recipientAddressDetail" character varying(200), "memo" character varying(200), "totalPrice" numeric(10,2), "orderedAt" TIMESTAMP, "trackingNumber" character varying(50), "carrierCode" character varying(30), "expectedPrintDate" date, "shippedAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1881ab845832ad82c4e45f5fe3b" UNIQUE ("idempotencyKey"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_orders_idempotency_key" ON "orders" ("idempotencyKey") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_orders_sweetbook_order_uid" ON "orders" ("sweetbookOrderUid") WHERE "sweetbookOrderUid" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_orders_status" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_orderer_id" ON "orders" ("ordererId") `);
        await queryRunner.query(`CREATE INDEX "idx_orders_order_group_id" ON "orders" ("orderGroupId") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "groupId" integer, "type" character varying(50) NOT NULL, "title" character varying(200) NOT NULL, "message" text, "isRead" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_read" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE INDEX "idx_notifications_user_id" ON "notifications" ("userId") `);
        await queryRunner.query(`CREATE TABLE "cover_candidates" ("id" SERIAL NOT NULL, "groupId" integer NOT NULL, "creatorUserId" integer NOT NULL, "photoId" integer, "title" character varying(60), "subtitle" character varying(60), "templateUid" character varying(50) NOT NULL, "bookSpecUid" character varying(50) NOT NULL, "templateName" character varying(120), "theme" character varying(60), "params" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b68ded3d8c1f569e8185c292132" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_ccand_group" ON "cover_candidates" ("groupId") `);
        await queryRunner.query(`CREATE TABLE "cover_votes" ("id" SERIAL NOT NULL, "candidateId" integer NOT NULL, "userId" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_384de81f613bd090310b659c922" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uniq_cvote" ON "cover_votes" ("candidateId", "userId") `);
        await queryRunner.query(`CREATE TABLE "personal_book_matches" ("id" SERIAL NOT NULL, "bookId" integer NOT NULL, "photoId" integer NOT NULL, "photoFaceId" integer, "similarity" double precision NOT NULL, "excludedByUser" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1e6520cdae44f46782eaacd548a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_personal_book_matches_book" ON "personal_book_matches" ("bookId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_personal_book_matches_book_photo" ON "personal_book_matches" ("bookId", "photoId") `);
        await queryRunner.query(`CREATE TABLE "group_activities" ("id" SERIAL NOT NULL, "groupId" integer NOT NULL, "actorUserId" integer, "type" character varying(40) NOT NULL, "payload" jsonb NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_95d0e7c0e65fe51b1f297a515af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_gact_group_created" ON "group_activities" ("groupId", "createdAt") `);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_1aa8d31831c3126947e7a713c2b" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_members" ADD CONSTRAINT "FK_fdef099303bcf0ffd9a4a7b18f5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_4d8d8897aef1c049336d8dde13f" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_df0d0b85eee65b9064b8e21a837" FOREIGN KEY ("parentGroupId") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_face_anchor_samples" ADD CONSTRAINT "FK_4559e7d9c5c6935a25569cd6e92" FOREIGN KEY ("anchorId") REFERENCES "user_face_anchors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_face_anchors" ADD CONSTRAINT "FK_b68b7e05292089c4e493c8b5139" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_face_anchors" ADD CONSTRAINT "FK_c0d57a18b1397a71d09ea141f35" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_c2ac86facbe1d417ab61226f70e" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photos" ADD CONSTRAINT "FK_62c5874d6ef9a7d51b6ffb38824" FOREIGN KEY ("uploaderId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photo_faces" ADD CONSTRAINT "FK_9171396deb3d0ddf81222fc5615" FOREIGN KEY ("photoId") REFERENCES "photos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "photo_faces" ADD CONSTRAINT "FK_0d861ed74a278b5d8fa4ab63792" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_pages" ADD CONSTRAINT "FK_b882d99c7dbf30e5e8c3a4f6823" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "book_pages" ADD CONSTRAINT "FK_7b9b84691b9c64f0f4d9083fe9f" FOREIGN KEY ("photoId") REFERENCES "photos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_b68c8a0bd3aa5ae10f67c339d21" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_f8adad35608098c5bd4e38a87fc" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_758130047bf01a87f8d2d28bc35" FOREIGN KEY ("ownerUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "books" ADD CONSTRAINT "FK_bf0b0a642936c73c93e1d8f00d7" FOREIGN KEY ("coverPhotoId") REFERENCES "photos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_groups" ADD CONSTRAINT "FK_3343f5e3104fdccbe45376f7112" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_groups" ADD CONSTRAINT "FK_e18f48794983fbba8821c76d2df" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_groups" ADD CONSTRAINT "FK_932041a80fecfab773dc96d3ada" FOREIGN KEY ("initiatedBy") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_a34ba12ea420c9bc02ae8fb6f6d" FOREIGN KEY ("orderGroupId") REFERENCES "order_groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_f50096d1ec235b11cbb05cd758f" FOREIGN KEY ("ordererId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_df2e025c7b9307b32e9cdfbbc10" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cover_candidates" ADD CONSTRAINT "FK_f95457e70f937ac3c1e504ef408" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cover_candidates" ADD CONSTRAINT "FK_34e6e68a3de28f067277d57598a" FOREIGN KEY ("creatorUserId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cover_candidates" ADD CONSTRAINT "FK_da8ed52856cee2651f571d21806" FOREIGN KEY ("photoId") REFERENCES "photos"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cover_votes" ADD CONSTRAINT "FK_a9b1d2662c8d2dd0af86ad86436" FOREIGN KEY ("candidateId") REFERENCES "cover_candidates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cover_votes" ADD CONSTRAINT "FK_7260757aaa3376e859254e116aa" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal_book_matches" ADD CONSTRAINT "FK_469f0f47d27cf14e28ee85d84e0" FOREIGN KEY ("bookId") REFERENCES "books"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal_book_matches" ADD CONSTRAINT "FK_53e4b96ce902450fbf37a7f95b4" FOREIGN KEY ("photoId") REFERENCES "photos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "personal_book_matches" ADD CONSTRAINT "FK_c56903bd8b11cd26ea44d435b2b" FOREIGN KEY ("photoFaceId") REFERENCES "photo_faces"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_activities" ADD CONSTRAINT "FK_566350269b41b975f055622a9bf" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_activities" ADD CONSTRAINT "FK_856b0510bd13624aca70f812c36" FOREIGN KEY ("actorUserId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "group_activities" DROP CONSTRAINT "FK_856b0510bd13624aca70f812c36"`);
        await queryRunner.query(`ALTER TABLE "group_activities" DROP CONSTRAINT "FK_566350269b41b975f055622a9bf"`);
        await queryRunner.query(`ALTER TABLE "personal_book_matches" DROP CONSTRAINT "FK_c56903bd8b11cd26ea44d435b2b"`);
        await queryRunner.query(`ALTER TABLE "personal_book_matches" DROP CONSTRAINT "FK_53e4b96ce902450fbf37a7f95b4"`);
        await queryRunner.query(`ALTER TABLE "personal_book_matches" DROP CONSTRAINT "FK_469f0f47d27cf14e28ee85d84e0"`);
        await queryRunner.query(`ALTER TABLE "cover_votes" DROP CONSTRAINT "FK_7260757aaa3376e859254e116aa"`);
        await queryRunner.query(`ALTER TABLE "cover_votes" DROP CONSTRAINT "FK_a9b1d2662c8d2dd0af86ad86436"`);
        await queryRunner.query(`ALTER TABLE "cover_candidates" DROP CONSTRAINT "FK_da8ed52856cee2651f571d21806"`);
        await queryRunner.query(`ALTER TABLE "cover_candidates" DROP CONSTRAINT "FK_34e6e68a3de28f067277d57598a"`);
        await queryRunner.query(`ALTER TABLE "cover_candidates" DROP CONSTRAINT "FK_f95457e70f937ac3c1e504ef408"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_df2e025c7b9307b32e9cdfbbc10"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_f50096d1ec235b11cbb05cd758f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_a34ba12ea420c9bc02ae8fb6f6d"`);
        await queryRunner.query(`ALTER TABLE "order_groups" DROP CONSTRAINT "FK_932041a80fecfab773dc96d3ada"`);
        await queryRunner.query(`ALTER TABLE "order_groups" DROP CONSTRAINT "FK_e18f48794983fbba8821c76d2df"`);
        await queryRunner.query(`ALTER TABLE "order_groups" DROP CONSTRAINT "FK_3343f5e3104fdccbe45376f7112"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_bf0b0a642936c73c93e1d8f00d7"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_758130047bf01a87f8d2d28bc35"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_f8adad35608098c5bd4e38a87fc"`);
        await queryRunner.query(`ALTER TABLE "books" DROP CONSTRAINT "FK_b68c8a0bd3aa5ae10f67c339d21"`);
        await queryRunner.query(`ALTER TABLE "book_pages" DROP CONSTRAINT "FK_7b9b84691b9c64f0f4d9083fe9f"`);
        await queryRunner.query(`ALTER TABLE "book_pages" DROP CONSTRAINT "FK_b882d99c7dbf30e5e8c3a4f6823"`);
        await queryRunner.query(`ALTER TABLE "photo_faces" DROP CONSTRAINT "FK_0d861ed74a278b5d8fa4ab63792"`);
        await queryRunner.query(`ALTER TABLE "photo_faces" DROP CONSTRAINT "FK_9171396deb3d0ddf81222fc5615"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_62c5874d6ef9a7d51b6ffb38824"`);
        await queryRunner.query(`ALTER TABLE "photos" DROP CONSTRAINT "FK_c2ac86facbe1d417ab61226f70e"`);
        await queryRunner.query(`ALTER TABLE "user_face_anchors" DROP CONSTRAINT "FK_c0d57a18b1397a71d09ea141f35"`);
        await queryRunner.query(`ALTER TABLE "user_face_anchors" DROP CONSTRAINT "FK_b68b7e05292089c4e493c8b5139"`);
        await queryRunner.query(`ALTER TABLE "user_face_anchor_samples" DROP CONSTRAINT "FK_4559e7d9c5c6935a25569cd6e92"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_df0d0b85eee65b9064b8e21a837"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_4d8d8897aef1c049336d8dde13f"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_fdef099303bcf0ffd9a4a7b18f5"`);
        await queryRunner.query(`ALTER TABLE "group_members" DROP CONSTRAINT "FK_1aa8d31831c3126947e7a713c2b"`);
        await queryRunner.query(`DROP INDEX "public"."idx_gact_group_created"`);
        await queryRunner.query(`DROP TABLE "group_activities"`);
        await queryRunner.query(`DROP INDEX "public"."idx_personal_book_matches_book_photo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_personal_book_matches_book"`);
        await queryRunner.query(`DROP TABLE "personal_book_matches"`);
        await queryRunner.query(`DROP INDEX "public"."uniq_cvote"`);
        await queryRunner.query(`DROP TABLE "cover_votes"`);
        await queryRunner.query(`DROP INDEX "public"."idx_ccand_group"`);
        await queryRunner.query(`DROP TABLE "cover_candidates"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_notifications_user_read"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_order_group_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_orderer_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_sweetbook_order_uid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_orders_idempotency_key"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_order_groups_group_id"`);
        await queryRunner.query(`DROP TABLE "order_groups"`);
        await queryRunner.query(`DROP TYPE "public"."order_groups_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_books_group_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_books_sweetbook_uid"`);
        await queryRunner.query(`DROP INDEX "public"."idx_books_share_code"`);
        await queryRunner.query(`DROP TABLE "books"`);
        await queryRunner.query(`DROP TYPE "public"."books_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."books_booktype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_book_pages_book_id"`);
        await queryRunner.query(`DROP TABLE "book_pages"`);
        await queryRunner.query(`DROP INDEX "public"."idx_photo_faces_photo"`);
        await queryRunner.query(`DROP INDEX "public"."idx_photo_faces_group"`);
        await queryRunner.query(`DROP TABLE "photo_faces"`);
        await queryRunner.query(`DROP INDEX "public"."idx_photos_group_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_photos_uploader_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_photos_group_chapter"`);
        await queryRunner.query(`DROP INDEX "public"."idx_photos_kakao_name"`);
        await queryRunner.query(`DROP TABLE "photos"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_face_anchors_user_group"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_face_anchors_group"`);
        await queryRunner.query(`DROP TABLE "user_face_anchors"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_face_anchor_samples_anchor"`);
        await queryRunner.query(`DROP TABLE "user_face_anchor_samples"`);
        await queryRunner.query(`DROP INDEX "public"."idx_groups_invite_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_groups_owner_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_groups_parent_group_id"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TYPE "public"."groups_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_group_members_group_user"`);
        await queryRunner.query(`DROP TABLE "group_members"`);
        await queryRunner.query(`DROP TYPE "public"."group_members_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_provider_lookup"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
